[package]
name = "math3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"
math3d_macro_derive = { path = "./math3d_macro_derive" }